def main():
    try:
        fp = open( "pollbuster.tpl" )
        tpl = fp.read()
    except (IOError, OSError):
        tpl = "{content}"

    content = """<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et dapibus diam. Aenean ornare adipiscing malesuada. Morbi laoreet ante non elit gravida fermentum at accumsan ligula. Maecenas at tristique tortor. Cras id luctus purus. In hac habitasse platea dictumst. Morbi vel sapien erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas bibendum velit eu neque semper interdum. In sed euismod est. Curabitur eget dolor nec elit commodo congue. Nunc sit amet quam mi. Curabitur ut orci sed neque ultricies feugiat ac at nisi. Aliquam erat volutpat. Sed lorem purus, feugiat vitae condimentum quis, egestas eget ante. Nulla facilisi. Ut mattis vehicula diam eget placerat. Integer in neque sed lectus dapibus varius at vitae dui. Praesent ligula neque, gravida vel egestas eget, bibendum vitae nisi. Morbi massa mi, vulputate dignissim interdum nec, feugiat et urna.</p>

<p>Ut velit nisl, congue aliquet lobortis in, viverra non erat. Sed ullamcorper imperdiet erat, non varius neque porta ac. Vivamus eleifend justo nec ipsum pharetra eget malesuada augue vestibulum. Integer mi felis, ullamcorper eu pretium eu, ullamcorper ultricies neque. Nulla luctus posuere sapien ac blandit. Sed tempus, leo at varius venenatis, est dui condimentum dolor, euismod gravida magna metus at nunc. Cras ac lectus a ante tincidunt faucibus. Proin vulputate blandit ipsum at tincidunt. Ut vitae lectus lectus, sed laoreet enim. Donec ullamcorper sagittis lectus, et sollicitudin velit convallis a. Proin leo ante, placerat sed volutpat vitae, condimentum venenatis mauris. Proin justo lectus, tincidunt vel auctor et, vulputate vel dui. In in commodo dui. Aliquam erat volutpat.</p>

<p>Suspendisse potenti. Etiam blandit placerat tellus, lacinia ornare velit vestibulum semper. Curabitur rutrum vestibulum neque, ac placerat libero rhoncus vel. Vestibulum posuere, elit quis fringilla scelerisque, mauris nibh luctus nunc, a suscipit lacus ante aliquam ante. Aliquam condimentum sagittis arcu semper iaculis. Nulla lobortis quam a nunc dignissim interdum. In rhoncus lorem nec metus euismod non faucibus tellus feugiat. Pellentesque quis interdum purus. Nulla eu leo tristique dui dapibus tempus. Nullam quam dui, mattis sed lacinia eget, vulputate ut elit. Fusce egestas dictum ante eu blandit. Proin rutrum arcu a leo porttitor quis ullamcorper massa sagittis. Donec viverra nulla ac urna blandit quis gravida lectus adipiscing. Phasellus vitae tortor sit amet quam convallis mollis. Cras rutrum fringilla vulputate. Pellentesque quis congue dui. Morbi eleifend quam eget justo tincidunt scelerisque.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent nulla elit, placerat eu euismod eu, hendrerit in orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc molestie auctor lacus, nec auctor leo suscipit at. Quisque turpis tellus, feugiat eget tempus ut, laoreet vitae purus. Aenean vel sapien sed sapien porta condimentum. Maecenas fermentum, justo sit amet lacinia faucibus, est nibh congue est, a pellentesque neque nisi at quam. Vestibulum dignissim semper neque vitae tempor. Ut sodales arcu nec quam malesuada tempus. Curabitur tempus tempor ante, a faucibus nisl eleifend vitae. Phasellus lacinia, justo ut tempus dignissim, arcu magna tincidunt enim, non tristique est dolor quis urna. Pellentesque tincidunt egestas tellus, a elementum arcu lobortis a. Etiam volutpat cursus lorem, ac fermentum leo dapibus ac. Morbi consectetur hendrerit sagittis. Morbi ultrices odio vitae dui molestie eget vulputate dui ultricies.</p>

<p>Suspendisse et nibh a magna semper consectetur nec nec est. Praesent id nunc turpis, nec ultrices dolor. Nam fringilla turpis sed mi placerat eget euismod nisl eleifend. Proin tempus gravida nibh, eget placerat arcu molestie ut. Nullam a leo vitae elit faucibus rutrum eget quis mauris. Mauris suscipit varius mauris id interdum. Sed neque nunc, tincidunt vel fermentum feugiat, ornare nec purus. Proin eget lorem blandit lectus scelerisque mattis. Fusce aliquet cursus est eget tincidunt. Aenean commodo varius lacus, eu gravida magna tristique vitae. Ut nec libero metus. Fusce at turpis vel turpis faucibus ullamcorper sed sed risus. Nulla facilisi. Etiam non velit vel elit adipiscing tristique id quis nisl. Cras varius tincidunt ultrices. Ut ac eros sem. Nam malesuada mollis leo, nec ullamcorper nunc imperdiet sed. Vestibulum ante justo, vulputate sed rhoncus in, posuere at arcu.</p>

<p>Vivamus porttitor euismod quam at bibendum. Nulla consectetur tempor sem, hendrerit rhoncus metus suscipit ut. Aenean in rutrum tortor. Pellentesque lacus odio, euismod ut semper ac, interdum nec tellus. Fusce sodales congue lectus, gravida sagittis dolor consectetur et. Aliquam suscipit dui lobortis tellus scelerisque euismod pharetra lorem fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed lacinia metus ut leo tempor eu facilisis metus venenatis. Proin porttitor ultrices feugiat. Proin convallis justo eu felis porta id mollis nisi eleifend. Cras ac consectetur sapien. Vivamus vel dui sapien.</p>

<p>Duis facilisis mattis bibendum. Ut fermentum nibh sit amet dui laoreet dictum. Mauris ornare posuere congue. Morbi sed erat tortor. Proin sit amet tellus turpis. Praesent porttitor scelerisque nunc, aliquam elementum metus scelerisque sed. Suspendisse ullamcorper blandit elit, non euismod libero adipiscing ut. Quisque eu molestie metus. Aenean sit amet libero massa. Sed ut enim velit, sed accumsan sapien. Sed eros risus, eleifend ut porta quis, dictum eu purus. Nunc fermentum sollicitudin erat at interdum. Curabitur augue orci, aliquet eu aliquam vel, pharetra vestibulum arcu. Quisque mollis est sit amet arcu fermentum aliquet. Mauris vitae dolor quis purus varius hendrerit et vitae arcu. Suspendisse potenti. Aliquam nisi lectus, tincidunt ut faucibus congue, semper sed quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

<p>Vivamus viverra feugiat tincidunt. Nunc tempus quam non quam cursus ornare. Nulla malesuada vestibulum lectus ut tempus. Nam viverra ligula non sem tincidunt quis commodo ante gravida. Maecenas at leo massa, et lobortis neque. Aliquam rutrum gravida dolor a vulputate. Sed dolor orci, venenatis et tristique vitae, elementum sit amet erat. Aliquam vitae metus purus, a mattis nulla. Cras risus diam, luctus vitae molestie ac, dictum in mi. Proin vel sapien at libero fringilla molestie vitae a eros. Fusce ullamcorper neque in nunc cursus accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum euismod mauris, nec placerat urna volutpat sit amet. Cras lobortis lacus in felis ornare lacinia. Nulla pharetra pharetra lectus non semper. Vestibulum lobortis lectus ornare felis vestibulum tincidunt. Maecenas pellentesque augue id eros viverra sodales consectetur magna lobortis. Integer purus neque, hendrerit quis volutpat eget, dapibus et urna. Sed dapibus nisi id est pulvinar faucibus.</p>

<p>Maecenas sit amet lacus ut sapien volutpat elementum. Maecenas sed nulla sed leo hendrerit tempor. Nullam pharetra imperdiet nibh, sed condimentum diam gravida vitae. Nam sodales, velit eu faucibus tempus, dui metus sodales augue, vel vulputate leo lorem vel nibh. Sed quis mollis sapien. Pellentesque pretium pretium eleifend. Proin congue sodales dui eu pretium. In elit mauris, aliquet at iaculis nec, posuere et quam. Nullam quis nisl in libero feugiat scelerisque dignissim non massa. Nulla facilisi. Fusce eget ultricies libero. Morbi pretium erat ut turpis mattis malesuada. Suspendisse pharetra aliquam rhoncus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam et erat eros.</p>

<p>Etiam diam justo, cursus vel aliquam at, fringilla ut tellus. Nunc sodales rhoncus pulvinar. Sed fermentum euismod neque, ut fringilla turpis ullamcorper a. Praesent quis risus nibh, sed pellentesque nisi. Nam porttitor, tortor id faucibus luctus, mauris velit ultricies leo, vitae aliquam magna nulla nec nibh. Sed sagittis sem ac elit tincidunt commodo. Cras placerat, sem vitae luctus accumsan, augue nunc ornare purus, non cursus neque odio at diam. Suspendisse tristique, lectus vel malesuada iaculis, velit orci porttitor risus, et sollicitudin mauris sem eu ipsum. Mauris volutpat justo in arcu aliquam laoreet. Nullam blandit porttitor diam et vehicula. Ut suscipit ultrices justo, non ultrices sem blandit eu. Quisque at arcu elit, porttitor tristique eros. In hac habitasse platea dictumst. In tincidunt, magna nec dapibus ullamcorper, dolor magna pharetra eros, at aliquam est turpis eget augue. Suspendisse velit mi, mollis vel molestie non, ullamcorper auctor nulla. Etiam eget mollis ipsum.</p>"""

    output = tpl.replace( "{content}", content.encode( "utf-8" ) )
    print "Content-Type: text/html"
    print "Content-Length:", len(output)
    print
    print output

if __name__ == "__main__":
    main()
